### ISSUE TITLE
Title page copy

### ISSUE THREAD

**Issue by fKunstner** [talks-tue/talks.tue.flask#33]
> **Frank:** Title page says: 
> "A simple way to find the best talks at hosted at our University for you."
> There is an additional "at" in there.

> **Fred:** Might also go for the simpler
> Talks hosted in Tübingen

---
**To Do**
* `talk/<id>`
    * [x] _Speaker's Bio_ -> _Speaker_
    * [x] _Speaker's Name_ -> _Speaker_
* `talks/`
    * [x] _Speaker's Name_ -> _Speaker_
    * [x] _Date/Time_ -> _Date_
* `/`
    * [x] _Register to build your profile_ -> _Register_
    * [x] maybe add _Login_ as well?

**Comment by fKunstner** [comment]
General copy suggestions;

* On `talk/id`
  * `Speaker's Bio` -> `Speaker`
  * `Speaker's name` -> `Speaker`
* `/talks` and `/subscriptions`
  * `Speaker's name` -> `Speaker`
  * `Date/Time` -> `Date`

**Comment by tim-fi** [comment]
will be available after deployment
