### ISSUE TITLE
`Browse > Talks` vs. `= > Upcoming Talks`

### ISSUE THREAD

**Issue by fKunstner** [talks-tue/talks.tue.flask#40]
> **Frank:** I found it a bit weird that there is a Talks tab under Browse, and then also a upcoming talks under the three bars. I get now what it is for. Maybe renaming it to "My Talks" or "Subscribed Talks" would help?

---
**To Do**
* [x] rename _upcoming talks_ to _subscribed talks_

**Comment by tim-fi** [comment]
will be available after deployment
