### ISSUE TITLE
Unclear utility of profile Category

### ISSUE THREAD

**Issue by fKunstner** [talks-tue/talks.tue.flask#41]
> **Frank:** Why can I add categories to my Profile?

---
**To Do**
* [x] remove category selection from user profile
* [x] remove category selection from talk form

**Comment by tim-fi** [comment]
Yeah I should temporarily remove this, we will support it in the future with a recommendation feature at least thats the plan atm.

**Comment by tim-fi** [comment]
will be available after deployment
