### ISSUE TITLE
Datetime formatting

### ISSUE THREAD

**Issue by fKunstner** [talks-tue/talks.tue.flask#43]
The datetime formatting should be standardized, probably to `dd/MM/yy HH:mm`

- On `/subscriptions` it is `MM/dd/yyyy`
- On `/talk/id` it is `yyyy-MM-dd HH-mm-ss`

---
**To Do**
* [x] render all datetimes in the backend
* [x] standardize datetime format
* [x] make consistent 
* [x] make format apply to talk form fields
* [x] remove `flask_moment` as a dependency

**Comment by tim-fi** [comment]
closed by 76daf689685b66a83ef74b876bed94068be427b4
