### ISSUE TITLE
UI Issue with Delete and Configure buttons

### ISSUE THREAD

**Issue by fKunstner** [talks-tue/talks.tue.flask#45]
Frank got that on a 4K res. at 125% Zoom.
I can reproduce on a 1080p (sorry I'm a peasant) at 200% zoom.

![UI-Bug-Talks-tue](https://user-images.githubusercontent.com/8789455/58898025-f3656d00-86f9-11e9-9bb7-aa554abdaaab.png)

Maybe just use a [X] and [Cog] icons? (e.g., https://fontawesome.com/icons/times,
https://fontawesome.com/icons/cog)

---
**To Do**
* [ ] use icons instead of words

**Comment by tim-fi** [comment]
will be addressed in #51
