### ISSUE TITLE
Show subscriptions options all at once in the profile page

### ISSUE THREAD

**Issue by wiseodd** [talks-tue/talks.tue.flask#48]
Instead of moving to a new page every time we want to reconfigure our subscription, I think it would be better to just show all the options (that are currently hidden behind "Configure" button) there, all at once. My rationale: There are not many options behind "Configure" button, and the cost of "context-switching" is therefore not justified.

Another option would be moving the configuration page onto a modal dialog.

**Comment by tim-fi** [comment]
This will be addressed using the changes proposed in #51.
