### ISSUE TITLE
Show editors and organizers real names instead of usernames

### ISSUE THREAD

**Issue by wiseodd** [talks-tue/talks.tue.flask#50]
Users (hence editors and organizers) can choose arbitrary usernames and it could get pretty confusing. E.g. when someone wants to see the quickly who's the organizer.

---
**To Do**
* [x] rename _username_ -> _display name_
* [x] use email as uuid instead of username
* [x] add disclaimer/warning to registration

**Comment by fKunstner** [comment]
Good point. Suggestion:
- Use the email as the login
- Ask for a "Display name" instead of a username

**Comment by tim-fi** [comment]
Yeah sounds like a good idea. 👍

**Comment by tim-fi** [comment]
addressed by #58
