### ISSUE TITLE
Can choose past dates when creating talk

### ISSUE THREAD

**Issue by wiseodd** [talks-tue/talks.tue.flask#55]
Should this be allowed?
If so, in the talk list, no time will be shown in this case.

![Screenshot from 2019-06-05 13-58-06](https://user-images.githubusercontent.com/2296722/58954627-0465bb00-879a-11e9-825d-b3e67483fd80.png)

---
**To Do**
* [x] add validation step to datetime in talk form

**Comment by tim-fi** [comment]
Good catch, I missed that one. 👍

**Comment by tim-fi** [comment]
addressed by #59
