### ISSUE TITLE
University Logo / CyberValley Logo

### ISSUE THREAD

**Issue by philipphennig** [talks-tue/talks.tue.flask#60]
The Logo of the University should be shown at the lop-left of the App. The CyberValley logo (CyberValley is funding this project) should be somewhere, too (probably top-right). 

The app should generally use the color scheme of the University (I send you a copy a while ago). 

These things seem minor, but they make a big difference in how the app is perceived (and how much credit we're getting for it). 

While you're at it, could you make sure to mention yourself and link our group somewhere? E.g. at the landing page, write "talks.tue is developed at the [Chair for the Methods of Machine Learning](http://mml.cs.uni-tuebingen.de). Lead dev: [Tim Fischer](your personal page). We are grateful for financial support by the [CyberValley Initiative](https://cyber-valley.de).

Best,

Philipp

---
**To Do**
* add about page
    * [x] add moml mention: [Chair for the Methods of Machine Learning](http://mml.cs.uni-tuebingen.de)
    * [x] add dev team: [Tim Fischer](your personal page), ...
    * [x] add cyber-valley mention: We are grateful for financial support by the [CyberValley Initiative](https://cyber-valley.de)
* adjust base template
    * [x] link to about page
    * [x] uni-logo
    * [x] cyber-valley logo
* [x] include color scheme

**Comment by tim-fi** [comment]
This is currently blocked by #66, because it will be easier to add theming using bootstrap.
The theme to use would be this one: [bootstrap_uni_theme.zip](https://github.com/talks-tue/talks.tue.flask/files/3443384/bootstrap_uni_theme.zip)
