### ISSUE TITLE
Subscriber Count stuck at 0

### ISSUE THREAD

**Issue by fsschneider** [talks-tue/talks.tue.flask#63]
Currently all collections have 0 subscribers:
![image](https://user-images.githubusercontent.com/12153723/61219235-154c0980-a714-11e9-93f7-f4f69e5bbd62.png)

However, I know that at least I am subscribed to 'AI Research Building'
![image](https://user-images.githubusercontent.com/12153723/61219295-34e33200-a714-11e9-9edb-ed77dbae1858.png)

The counter is zero on the page of the collection as well.

---
**To Do**
* [x] investigate
* [x] use `len` instead of `count`

**Comment by tim-fi** [comment]
Wrong button...
